variables:
  hostname:
    required: true
    description: Some hostname

  buffer_size:
    required: false
    default: 1024
    description: Buffer size

  load_balancer_hostname:
    required: false
    default: alb.{{ hostname }}
    description: Load balancer hostname 
